### ISSUE TITLE
Nodes do not parse /etc/openshift/logshifter.conf

### ISSUE THREAD

**Issue by IshentRas** [openshift/puppet-openshift_origin#383]
/etc/openshift/logshifter.conf is generated from an ERB file located "templates/node/logshifter.conf.erb"
Because of spaces nodes do not parse the file and do not log in the directory "filewriterdir"

Solution: use trim_mode (Adding a "-" before the ERB closing mark-up "%>") within the if statement so as to avoid extra lines.
<% if scope.lookupvar('::openshift_origin::syslog_enabled') == true -%>
outputtype = multi
<% else -%>
outputtype = file
<% end -%>

**Comment by sdodson** [comment]
Fixed in #385
