### ISSUE TITLE
File /etc/openshift/logshifter.conf should be applied once rubygem-openshift-origin-node is installed

### ISSUE THREAD

**Issue by IshentRas** [openshift/puppet-openshift_origin#384]
The resource file /etc/openshift/logshifter.conf should be applied once rubygem-openshift-origin-node is installed in the file located in "manifests/rsyslog/node.pp"

Without the require function, it fails to apply.

file { '/etc/openshift/logshifter.conf':
    ensure  => 'file',
    owner   => 'root',
    group   => 'root',
    content => template('openshift_origin/node/logshifter.conf.erb'),
    require => Package['rubygem-openshift-origin-node'],
    notify  => [Service['openshift-watchman'], Service["${::openshift_origin::params::ruby_scl_prefix}mcollective"]]
  }

**Comment by sdodson** [comment]
Fixed in #385
