### ISSUE TITLE
OpenShift V3

### ISSUE THREAD

**Issue by roldancer** [openshift/puppet-openshift_origin#389]
Hi All, Is there any plan to support OpenShift V3 ? if so, when ?

**Comment by andrewklau** [comment]
Work's being done in ansible so far https://github.com/openshift/openshift-ansible

**Comment by sdodson** [comment]
Andrew is correct, at this point in time we're focused on the ansible installer. If Red Hat works on a puppet module for v3 it will be a new module and will likely only happen after 3.0 GA.

**Comment by lowwool** [comment]
So as of right now, are there still no plans for creating a puppet module for OpenShift V3?

**Comment by sdodson** [comment]
That's correct.
