### ISSUE TITLE
PROXY_PORTS_PER_GEAR vs PORTS_PER_USER

### ISSUE THREAD

**Issue by sdodson** [openshift/puppet-openshift_origin#397]
Per https://github.com/openshift/origin-server/commit/18a380023392daadd0a5c8da96fb8f6ea1b5b08f there's been a change in config variables between M4 and more recent OSE releases. Need to conditionalize things based on ose_version

**Comment by sdodson** [comment]
Related to #392

**Comment by IshentRas** [comment]
I have just checked and I am 100% sure that OpenShift Origin has not changed the option names/values.
 Therefore, we shall propose new conditional statements based on ose_version parameter (::openshift_origin::ose_version) so as to determine when we should applied new naming convention or not.

**Comment by IshentRas** [comment]
The same is also valid for broker.conf

**Comment by IshentRas** [comment]
https://github.com/openshift/puppet-openshift_origin/pull/398
